apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-enterprise-config
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
  annotations:
    {{- if .Values.enterprise.config.horizontalScaling.enabled }}
    scaling/enabled: "true"
    {{- end }}
    purpose: "enterprise-configuration"
data:
  # Horizontal Scaling
  HORIZONTAL_SCALING: {{ .Values.enterprise.config.horizontalScaling.enabled | quote }}

  # URLs and Frontend Config
  VITE_BASE_URL: {{ .Values.enterprise.config.urls.base | quote }}
  VITE_SHORTCODE_BASE_URL: {{ .Values.enterprise.config.urls.shortcode | quote }}
  VITE_ADMIN_URL: {{ .Values.enterprise.config.urls.admin | quote }}
  VITE_BACKEND_GQL_URL: {{ .Values.enterprise.config.urls.backend.gql | quote }}
  VITE_BACKEND_WS_URL: {{ .Values.enterprise.config.urls.backend.ws | quote }}
  VITE_BACKEND_API_URL: {{ .Values.enterprise.config.urls.backend.api | quote }}
  WHITELISTED_ORIGINS: {{ .Values.enterprise.config.urls.whitelistedOrigins | quote }}

  # Proxy
  LOCAL_PROXY_SERVER_ENABLE: {{ .Values.enterprise.config.proxy.localProxyServerEnabled | quote }}
  PROXY_APP_URL: {{ .Values.enterprise.config.proxy.appUrl | quote }}
  VITE_PROXYSCOTCH_ACCESS_TOKEN: {{ .Values.enterprise.config.proxy.proxyscotchAccessToken | quote }}
  TRUST_PROXY: {{ .Values.enterprise.config.trustProxy | quote }}

  # Enterprise Config
  ENABLE_SUBPATH_BASED_ACCESS: {{ .Values.enterprise.config.enterprise.enableSubpathBasedAccess | quote }}

  # Links
  VITE_APP_TOS_LINK: {{ .Values.enterprise.config.links.tos | quote }}
  VITE_APP_PRIVACY_POLICY_LINK: {{ .Values.enterprise.config.links.privacyPolicy | quote }}
