apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-community-config
data:
  # Database
  DATABASE_URL: {{ if .Values.community.config.database.external }}{{ .Values.community.config.database.url | quote }}{{ else }}{{ printf "postgres://%s:%s@%s-postgresql:5432/%s?sslmode=disable" .Values.community.config.postgresql.username .Values.community.config.postgresql.password .Release.Name .Values.community.config.postgresql.database | quote }}{{ end }}

  # Mailer
  MAILER_SMTP_ENABLE: {{ .Values.community.config.mailer.enable | quote }}
  MAILER_USE_CUSTOM_CONFIGS: {{ .Values.community.config.mailer.useCustomConfigs | quote }}
  MAILER_ADDRESS_FROM: {{ .Values.community.config.mailer.addressFrom | quote }}
  MAILER_SMTP_URL: {{ .Values.community.config.mailer.smtp.url | quote }}
  MAILER_SMTP_HOST: {{ .Values.community.config.mailer.smtp.host | quote }}
  MAILER_SMTP_PORT: {{ .Values.community.config.mailer.smtp.port | quote }}
  MAILER_SMTP_SECURE: {{ .Values.community.config.mailer.smtp.secure | quote }}
  MAILER_SMTP_USER: {{ .Values.community.config.mailer.smtp.user | quote }}
  MAILER_SMTP_PASSWORD: {{ .Values.community.config.mailer.smtp.password | quote }}
  MAILER_TLS_REJECT_UNAUTHORIZED: {{ .Values.community.config.mailer.smtp.tlsRejectUnauthorized | quote }}

  # Rate Limit
  RATE_LIMIT_TTL: {{ .Values.community.config.rateLimit.ttl | quote }}
  RATE_LIMIT_MAX: {{ .Values.community.config.rateLimit.max | quote }}

  # Auth Tokens
  SESSION_SECRET: {{ .Values.community.config.authjwt.sessionSecret | quote }}
  JWT_SECRET: {{ .Values.community.config.authjwt.jwtSecret | quote }}
  TOKEN_SALT_COMPLEXITY: {{ .Values.community.config.authjwt.tokenSaltComplexity | quote }}
  MAGIC_LINK_TOKEN_VALIDITY: {{ .Values.community.config.authjwt.magicLinkTokenValidity | quote }}
  REFRESH_TOKEN_VALIDITY: {{ .Values.community.config.authjwt.refreshTokenValidity | quote }}
  ACCESS_TOKEN_VALIDITY: {{ .Values.community.config.authjwt.accessTokenValidity | quote }}
  ALLOW_SECURE_COOKIES: {{ .Values.community.config.authjwt.allowSecureCookies | quote }}
  DATA_ENCRYPTION_KEY: {{ .Values.community.config.authjwt.dataEncryptionKey | quote }}

  # URLs and Frontend Config
  {{ $protocol := .Values.community.config.urls.https | ternary "https" "http" -}}
  {{ $wsprotocol := .Values.community.config.urls.https | ternary "wss" "ws" -}}
  {{- $base_url := printf "%s://%s" $protocol .Values.service.ingress.mainHost -}}
  {{- $admin_url := printf "%s://%s" $protocol ( .Values.community.config.community.enableSubpathBasedAccess | ternary (printf "%s/admin" .Values.service.ingress.mainHost) .Values.service.ingress.adminHost ) -}}
  {{- $backend_url := .Values.community.config.community.enableSubpathBasedAccess | ternary (printf "%s/backend" .Values.service.ingress.mainHost) .Values.service.ingress.backendHost -}}
  {{- $http_backend_url := printf "%s://%s" $protocol $backend_url -}}
  {{- $url_underscore := (.Values.service.ingress.mainHost | replace "." "_") -}}
  {{- $app_url := printf "app://%s,http://app.%s" $url_underscore $url_underscore -}}

  VITE_BASE_URL: {{ .Values.community.config.urls.base | default $base_url | quote }}
  VITE_SHORTCODE_BASE_URL: {{ .Values.community.config.urls.shortcode | default $base_url | quote }}
  REDIRECT_URL: {{ .Values.community.config.urls.base | default $base_url | quote }}
  VITE_ADMIN_URL: {{ .Values.community.config.urls.admin | default $admin_url | quote }}
  VITE_BACKEND_GQL_URL: {{ .Values.community.config.urls.backend.gql | default (printf "%s/graphql" $http_backend_url) | quote }}
  VITE_BACKEND_WS_URL: {{ .Values.community.config.urls.backend.ws | default (printf "%s://%s/graphql" $wsprotocol $backend_url) | quote }}
  VITE_BACKEND_API_URL: {{ .Values.community.config.urls.backend.api | default (printf "%s/v1" $http_backend_url) | quote }}
  WHITELISTED_ORIGINS: {{ printf "%s,%s,%s,%s,%s" $base_url $admin_url $http_backend_url $app_url (.Values.community.config.urls.whitelistedOrigins | default "") | quote }}

  # Google Auth
  GOOGLE_CLIENT_ID: {{ .Values.community.config.auth.google.clientId | quote }}
  GOOGLE_CLIENT_SECRET: {{ .Values.community.config.auth.google.clientSecret | quote }}
  GOOGLE_CALLBACK_URL: {{ .Values.community.config.auth.google.callbackUrl | quote }}
  GOOGLE_SCOPE: {{ .Values.community.config.auth.google.scope | quote }}

  # Github Auth
  GITHUB_CLIENT_ID: {{ .Values.community.config.auth.github.clientId | quote }}
  GITHUB_CLIENT_SECRET: {{ .Values.community.config.auth.github.clientSecret | quote }}
  GITHUB_CALLBACK_URL: {{ .Values.community.config.auth.github.callbackUrl | quote }}
  GITHUB_SCOPE: {{ .Values.community.config.auth.github.scope | quote }}

  # Microsoft Auth
  MICROSOFT_CLIENT_ID: {{ .Values.community.config.auth.microsoft.clientId | quote }}
  MICROSOFT_CLIENT_SECRET: {{ .Values.community.config.auth.microsoft.clientSecret | quote }}
  MICROSOFT_CALLBACK_URL: {{ .Values.community.config.auth.microsoft.callbackUrl | quote }}
  MICROSOFT_SCOPE: {{ .Values.community.config.auth.microsoft.scope | quote }}
  MICROSOFT_TENANT: {{ .Values.community.config.auth.microsoft.tenant | quote }}

  # community Config
  VITE_ALLOWED_AUTH_PROVIDERS: {{ .Values.community.config.auth.allowedProviders | quote }}
  ENABLE_SUBPATH_BASED_ACCESS: {{ .Values.community.config.community.enableSubpathBasedAccess | quote }}

  # Links
  VITE_APP_TOS_LINK: {{ .Values.community.config.links.tos | quote }}
  VITE_APP_PRIVACY_POLICY_LINK: {{ .Values.community.config.links.privacyPolicy | quote }}