apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-community-config
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
  annotations:
    purpose: "community-configuration"
data:
  # URLs and Frontend Config
  VITE_BASE_URL: {{ .Values.community.config.urls.base | quote }}
  VITE_SHORTCODE_BASE_URL: {{ .Values.community.config.urls.shortcode | quote }}
  VITE_ADMIN_URL: {{ .Values.community.config.urls.admin | quote }}
  VITE_BACKEND_GQL_URL: {{ .Values.community.config.urls.backend.gql | quote }}
  VITE_BACKEND_WS_URL: {{ .Values.community.config.urls.backend.ws | quote }}
  VITE_BACKEND_API_URL: {{ .Values.community.config.urls.backend.api | quote }}
  WHITELISTED_ORIGINS: {{ .Values.community.config.urls.whitelistedOrigins | quote }}

  # Proxy
  PROXY_APP_URL: {{ .Values.community.config.proxy.appUrl | quote }}
  VITE_PROXYSCOTCH_ACCESS_TOKEN: {{ .Values.community.config.proxy.proxyscotchAccessToken | quote }}
  TRUST_PROXY: {{ .Values.community.config.trustProxy | quote }}

  # Community Config
  ENABLE_SUBPATH_BASED_ACCESS: {{ .Values.community.config.community.enableSubpathBasedAccess | quote }}

  # Links
  VITE_APP_TOS_LINK: {{ .Values.community.config.links.tos | quote }}
  VITE_APP_PRIVACY_POLICY_LINK: {{ .Values.community.config.links.privacyPolicy | quote }}
