{{- if not .Values.community.config.auth.existingSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-auth-config
  namespace: {{ .Release.Namespace | quote }}
type: Opaque
data:
  GOOGLE_CLIENT_ID: {{ .Values.community.config.auth.google.clientId | b64enc | quote }}
  GOOGLE_CLIENT_SECRET: {{ .Values.community.config.auth.google.clientSecret | b64enc | quote }}
  GOOGLE_CALLBACK_URL: {{ .Values.community.config.auth.google.callbackUrl | b64enc | quote }}
  GOOGLE_SCOPE: {{ .Values.community.config.auth.google.scope | b64enc | quote }}

  # Github Auth
  GITHUB_CLIENT_ID: {{ .Values.community.config.auth.github.clientId | b64enc | quote }}
  GITHUB_CLIENT_SECRET: {{ .Values.community.config.auth.github.clientSecret | b64enc | quote }}
  GITHUB_CALLBACK_URL: {{ .Values.community.config.auth.github.callbackUrl | b64enc | quote }}
  GITHUB_SCOPE: {{ .Values.community.config.auth.github.scope | b64enc | quote }}

  # Microsoft Auth
  MICROSOFT_CLIENT_ID: {{ .Values.community.config.auth.microsoft.clientId | b64enc | quote }}
  MICROSOFT_CLIENT_SECRET: {{ .Values.community.config.auth.microsoft.clientSecret | b64enc | quote }}
  MICROSOFT_CALLBACK_URL: {{ .Values.community.config.auth.microsoft.callbackUrl | b64enc | quote }}
  MICROSOFT_SCOPE: {{ .Values.community.config.auth.microsoft.scope | b64enc | quote }}
  MICROSOFT_TENANT: {{ .Values.community.config.auth.microsoft.tenant | b64enc | quote }}
{{- end }}

{{- if not .Values.community.config.postgresql.existingSecret.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-db
  namespace: {{ .Release.Namespace | quote }}
type: Opaque
data:
  {{- if .Values.community.config.database.external }}
  db-url: {{ .Values.community.config.database.url | b64enc | quote }}
  {{- else }}
  db-url: {{ printf "postgresql://%s:%s@%s-postgresql:5432/%s?schema=public" .Values.community.config.postgresql.username .Values.community.config.postgresql.password .Release.Name .Values.community.config.postgresql.database }}
  {{- end }}
  db-username: {{ .Values.community.config.postgresql.username | b64enc | quote }}
  db-password: {{ .Values.community.config.postgresql.password | b64enc | quote }}
{{- end }}
