apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-community-secrets
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
type: Opaque
data:
  # Database
  DATABASE_URL: {{ if .Values.community.config.database.external }}{{ .Values.community.config.database.url | b64enc }}{{ else }}{{ printf "postgresql://%s:%s@%s-postgresql:5432/%s?schema=public" .Values.community.config.postgresql.username .Values.community.config.postgresql.password .Release.Name .Values.community.config.postgresql.database | b64enc }}{{ end }}

  # Data Encryption
  DATA_ENCRYPTION_KEY: {{ .Values.community.config.dataEncryptionKey | b64enc }}
