apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hoppscotch.fullname" . }}
  namespace: {{ include "hoppscotch.namespace" . | quote }}
  labels:
    app.kubernetes.io/component: hoppscotch
    {{- include "hoppscotch.labels" . | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations:
    {{- toYaml .Values.commonAnnotations | nindent 4 }}
  {{- end }}
data:
  {{- if eq .Values.deploymentMode "aio" }}
  ENABLE_SUBPATH_BASED_ACCESS: {{ .Values.hoppscotch.frontend.enableSubpathBasedAccess | quote }}
  {{- else }}
  ENABLE_SUBPATH_BASED_ACCESS: "false"
  {{- end }}
  HOPP_AIO_ALTERNATE_PORT: {{ .Values.hoppscotch.backend.aioAlternatePort | quote }}
  HORIZONTAL_SCALING: {{ .Values.hoppscotch.backend.horizontalScalingEnabled | quote }}
  LOCAL_PROXY_SERVER_ENABLE: {{ .Values.hoppscotch.frontend.localProxyServerEnabled | quote }}
  PROXY_APP_URL: {{ .Values.hoppscotch.frontend.proxyAppUrl | quote }}
  TRUST_PROXY: {{ .Values.hoppscotch.backend.trustProxy | quote }}
  VITE_ADMIN_URL: {{ include "hoppscotch.frontend.adminUrl" . | quote }}
  VITE_APP_PRIVACY_POLICY_LINK: {{ .Values.hoppscotch.frontend.appPrivacyPolicyLink | quote }}
  VITE_APP_TOS_LINK: {{ .Values.hoppscotch.frontend.appTosLink | quote }}
  VITE_BACKEND_API_URL: {{ include "hoppscotch.frontend.backendApiUrl" . | quote }}
  VITE_BACKEND_GQL_URL: {{ include "hoppscotch.frontend.backendGqlUrl" . | quote }}
  VITE_BACKEND_WS_URL: {{ include "hoppscotch.frontend.backendWsUrl" . | quote }}
  VITE_BASE_URL: {{ include "hoppscotch.frontend.baseUrl" . | quote }}
  VITE_PROXYSCOTCH_ACCESS_TOKEN: {{ .Values.hoppscotch.frontend.proxyscotchAccessToken | quote }}
  VITE_SHORTCODE_BASE_URL: {{ include "hoppscotch.frontend.shortcodeBaseUrl" . | quote }}
  WHITELISTED_ORIGINS: {{ include "hoppscotch.backend.whitelistedOrigins" . | quote }}
