{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hoppscotch.fullname" . }}
  namespace: {{ include "hoppscotch.namespace" . | quote }}
  labels:
    app.kubernetes.io/component: hoppscotch
    {{- include "hoppscotch.labels" . | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations:
    {{- toYaml .Values.commonAnnotations | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{- with .Values.hoppscotch.backend }}
  DATABASE_URL: {{ include "hoppscotch.secret.databaseUrl" $ | b64enc | quote }}
  DATA_ENCRYPTION_KEY: {{ include "hoppscotch.secret.dataEncryptionKey" $ | b64enc | quote }}
  ENTERPRISE_LICENSE_KEY: {{ .enterpriseLicenseKey | b64enc | quote }}
  {{- if .horizontalScalingEnabled }}
  REDIS_URL: {{ include "hoppscotch.secret.redisUrl" $ | b64enc | quote }}
  {{- end }}
  {{- end }}
{{- end }}
